# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Doc-Mate API
  description: Doc-Mate REST API documentation.
  version: "1.0.0"
# the domain of the service
host: api.doc-mate.goodfoot.io
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://doc-mate.goodfoot.io/authorization'
    tokenUrl: 'https://doc-mate.goodfoot.io/token'
security:
  - OauthSecurity: []
paths:
  /company:
    get:
      summary: Company Profile
      description: The Company Profile endpoint returns information about the company associated with the user that has authorized with the application.
      tags:
        - Company
      responses:
        200:
          description: Profile information for a company.
          schema:
            $ref: '#/definitions/Company'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /me:
    get:
      summary: Authorized User Profile
      description: The Authorized User Profile endpoint returns information about the user that has authorized with the application.
      tags:
        - User
      responses:
        200:
          description: Profile information for a user.
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /user/{uuid}:
    get:
      summary: User Profile
      description: The User Profile endpoint returns information about a user.
      parameters:
      - name: uuid
        in: path
        description: The UUID of the user.
        required: true
        type: string
      tags:
        - User
      responses:
        200:
          description: Profile information for a user.
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /site/{uuid}:
    get:
      summary: Site
      description: The Site endpoint returns information about a site.
      parameters:
      - name: uuid
        in: path
        description: The UUID of the site.
        required: true
        type: string
      tags:
        - Site
      responses:
        200:
          description: Information about a site.
          schema:
            $ref: '#/definitions/Site'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /site/{uuid}/comments:
    get:
      summary: Site Comments
      description: The Site Comments endpoint returns comments on a site.
      parameters:
      - name: uuid
        in: path
        description: The UUID of the site.
        required: true
        type: string
      tags:
        - Site
      responses:
        200:
          description: Comments on a site.
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /job/{uuid}:
    get:
      summary: Job
      description: The Job endpoint returns information about a job.
      parameters:
      - name: uuid
        in: path
        description: The UUID of the job.
        required: true
        type: string
      tags:
        - Job
      responses:
        200:
          description: Information about a job.
          schema:
            $ref: '#/definitions/Job'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /job/{uuid}/comments:
    get:
      summary: Job Comments
      description: The Job Comments endpoint returns comments on a job.
      parameters:
      - name: uuid
        in: path
        description: The UUID of the job.
        required: true
        type: string
      tags:
        - Job
      responses:
        200:
          description: Comments on a job.
          schema:
            type: array
            items:
              $ref: '#/definitions/Comment'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /comment/{uuid}:
    get:
      summary: Comment
      description: The Comment endpoint returns information about a comment.
      parameters:
      - name: uuid
        in: path
        description: The UUID of the comment.
        required: true
        type: string
      tags:
        - Comment
      responses:
        200:
          description: Information about a comment.
          schema:
            $ref: '#/definitions/Comment'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Company:
    type: object
    properties:
      uuid:
        type: string
        format: uuid
        description: Unique identifier for the company.
      name:
        type: string
        description: Name of the company.
      address:
        $ref: "#/definitions/Address"
  User:
    type: object
    properties:
      uuid:
        type: string
        format: uuid
        description: Unique identifier for the user.
      first_name:
        type: string
        description: First name of the user.
      last_name:
        type: string
        description: Last name of the user.
      biography:
        type: string
        description: Biography of the user.
      email:
        type: string
        format: email
        description: Email address of the user.
      profile_image_url:
        type: string
        description: URL of the user's avatar image.
  Site:
    type: object
    properties:
      uuid:
        type: string
        format: uuid
        description: Unique identifier for the site.
      name:
        type: string
        description: Name of the site.
      address:
        $ref: "#/definitions/Address"
      latitude:
        type: number
        format: double
        description: Latitude component of site location.
      longitude:
        type: number
        format: double
        description: Longitude component of site location.
      created:
        type: string
        format: date-time
        description: Time of site creation.
      owner:
        $ref: "#/definitions/User"
  Job:
    type: object
    properties:
      uuid:
        type: string
        format: uuid
        description: Unique identifier for the job.
      created:
        type: string
        format: date-time
        description: Time of job creation.
      estimated_origin_arrival:
        type: string
        format: date-time
        description: Time of estimated arrival at the origin site.
      estimated_destination_arrival:
        type: string
        format: date-time
        description: Time of estimated arrival at the destination site.
      origin:
        $ref: "#/definitions/Site"
      destination:
        $ref: "#/definitions/Site"
      driver:
        $ref: "#/definitions/User"
      exceptions:
        type: array
        description: Exceptions associated with the job.
        items:
          $ref: "#/definitions/Exception"
  Comment:
    type: object
    properties:
      uuid:
        type: string
        format: uuid
        description: Unique identifier for the comment.
      created:
        type: string
        format: date-time
        description: Time of site creation.
      author:
        $ref: "#/definitions/User"
      text:
        type: string
        description: Text of the comment.
      src_url:
        type: string
        description: URL of content to be embedded in the comment.
      deleted:
        type: boolean
        description: true if the comment has been deleted.
      parent_uuid:
        type: string
        description: UUID of the comment's parent.
      child_uuids:
        type: array
        description: UUIDs of the comment's children.
        items:
          type: string
      score:
        type: integer
        format: int32
        description: Score of the comment.
  Exception:
    type: object
    properties:
      uuid:
        type: string
        format: uuid
        description: Unique identifier for the exception.
      created:
        type: string
        format: date-time
        description: Time of exception creation.
      completed:
        type: string
        format: date-time
        description: Time of exception completion.
      owner:
        $ref: "#/definitions/User"
      description:
        type: string
        description: Description of the exception.
      latitude:
        type: number
        format: double
        description: Latitude component of the exception location.
      longitude:
        type: number
        format: double
        description: Longitude component of the exception location.
      address:
        $ref: "#/definitions/Address"
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  Address:
    type: object
    properties:
      street:
        type: string
        description: Street line of the address.
      street2:
        type: string
        description: Extra information about the address.
      city:
        type: string
        description: City name of the address.
      state:
        type: string
        description: State name or abbreviation of the address.
      zipcode:
        type: string
        description: ZIP code of the address.